name: dr_tech
description: A new Flutter project. 
publish_to: 'none' 
version: 5.0.28+78
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_local_notifications: ^9.1.4
  flutter_cupertino_localizations: ^1.0.1
  shared_preferences: ^2.0.0
  cached_network_image: ^3.0.0
  http:
  intl:
  flutter_icons:
  flutter_svg: ^1.0.3
  flutter_sim_country_code: ^0.1.2
  keyboard_visibility: ^0.5.6
  vibration: ^1.7.3
  webview_flutter: ^3.0.2
  flutter_webview_plugin: ^0.4.0
  url_launcher: ^6.0.0
  firebase_core:
  firebase_messaging:
  firebase_analytics:
  firebase_crashlytics:
  assets_audio_player: ^3.0.3+6
  share: ^2.0.4
  # Pickers
  image_picker: ^0.8.5
  file_picker: ^4.5.1
  firebase_auth:
  package_info_plus: ^1.0.6
#  geolocation: ^1.1.2
  popup_menu: ^1.0.5
  cupertino_icons: ^1.0.2
  number_to_word_arabic: ^0.0.8
  flutter_inapp_purchase: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter 
flutter: 
  uses-material-design: true 
  assets:
    - assets/images/
    - assets/icons/
    - assets/illustration/
    - assets/sounds/
  fonts: 
  - family: Cario
    fonts:
      - asset: assets/fonts/Cairo-ExtraLight.ttf
        weight: 100
      - asset: assets/fonts/Cairo-Light.ttf
        weight: 200
      - asset: assets/fonts/Cairo-Regular.ttf
        weight: 300
      - asset: assets/fonts/Cairo-Black.ttf
        weight: 400
      - asset: assets/fonts/Cairo-SemiBold.ttf
        weight: 500
      - asset: assets/fonts/Cairo-Bold.ttf
        weight: 600

module:
  androidX: true # Add this line.